config/routes.rb
Rails.application.routes.draw do

  root 'games#home'
  resources :games

end

app/models/game.rb
class Game < ActiveRecord::Base

  # MODEL
  # t.string :title
  # t.string :platform
  # t.integer :year
  # t.string :gender
  # t.float :price
  # t.integer :rating


  ## VALIDATIONS ##

  # title
  validates_presence_of :title, message: "não pode ser vazio"
  validates_uniqueness_of :title, message: "já existe"

  # platform
  validates_presence_of :platform, message: "não pode ser vazio"

  # year
  validates_presence_of :year, message: "não pode ser vazio"
  validates_numericality_of :year, only_integer: true, message: "deve conter apenas números"
  validates_length_of :year,  is: 4, message: "deve possuir exatamente 4 digitos"

  # gender
  validates_presence_of :gender, message: "não pode ser vazio"

  # price
  validates_presence_of :price, message: "não pode ser vazio"

  # rating
  validates_presence_of :rating, message: "não pode ser vazio"
  validates_numericality_of :rating, only_integer: true, less_than: 6, message: "deve possuir valor até 5"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include ActionView::Helpers::TextHelper

  def index
    @game = Game.all
    @gamesPrice = Game.sum(:price)
    @games_grid = initialize_grid(Game,
                                  order:           'games.rating',
                                  order_direction: 'desc',
                                  per_page: 5
    )
  end

  def new
    @game = Game.new
  end

  def show
    @game = Game.find(params[:id])
  end

  def create
    @game = Game.new(game_params)    # Not the final implementation!
    if @game.save
      # Handle a successful save.
      redirect_to games_path
    elsif @game.errors.any?
      render 'new'
    end
  end

  # definimos game_params caso precisemos restringir certas rows de serem inseridas via http
  private
  def game_params
    params.require(:game).permit(:title, :platform, :gender, :year, :price, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/home.html.erb
<%# Pagina Home %>
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand"><%= link_to "Game Library", root_path %></h3>
    <nav>
      <ul class="nav masthead-nav">
        <li class="active"><%= link_to "Home", root_path %></a></li>
        <li><%= link_to "Games", games_path %></li>
        <li> <%= link_to "Add Game", new_game_path %></li>
      </ul>
    </nav>
  </div>
</div>
<div class="inner cover">
  <h1 class="cover-heading">Games Library</h1>
  <p class="lead">A place to organize my games</p>
  <p class="lead">
    <%= link_to ('<button class="btn btn-lg btn-default">View Games</button>').html_safe, games_path %>
    <%= link_to ('<button class="btn btn-lg btn-default">Add Game</button>').html_safe, new_game_path %>
  </p>
</div>

app/views/games/index.html.erb
<%# Pagina Que lista todos os jogos %>

<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand"><%= link_to "Game Library", root_path %></h3>
    <nav>
      <ul class="nav masthead-nav">
        <li><%= link_to "Home", root_path %></a></li>
        <li class="active"><%= link_to "Games", games_path %></li>
        <li> <%= link_to "Add Game", new_game_path %></li>
      </ul>
    </nav>
  </div>
</div>

<div class="inner cover">
  <h1 class="cover-heading">Game list</h1>
  <br>
</div>

<%# Definicao do grid que gera a tabela com filtros %>

<%= define_grid(@games_grid, show_filters: :always,  hide_submit_button: true, hide_reset_button: true) do |g|

  g.column name: 'Title', attribute: 'title', detach_with_id: :title_filter, custom_filter: :auto

  g.column name: 'Platform', attribute: 'platform', detach_with_id: :platform_filter, custom_filter: :auto

  g.column name: 'Year', attribute: 'year', detach_with_id: :year_filter, custom_filter: :auto

  g.column name: 'Gender', attribute: 'gender', detach_with_id: :gender_filter, filter: false

  g.column name: 'Price', attribute: 'price', detach_with_id: :price_filter, filter: false

  g.column name: 'Rating', attribute: 'rating', detach_with_id: :rating_filter, filter: false

end %>

<div class="row">
  <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
    <label>Title Filter</label>
    <%= grid_filter @games_grid, :title_filter %>
  </div>
  <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
    <label>Platform Filter</label>
    <%= grid_filter @games_grid, :platform_filter %>
  </div>
  <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
    <label>Year Filter</label>
    <%= grid_filter @games_grid, :year_filter %>
  </div>
  <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
    <label>Controls</label><br>
    <button class="btn btn-sm btn-default wg-external-submit-button" data-grid-name="grid">Submit</button>
    <button class="btn btn-sm btn-default wg-external-reset-button" data-grid-name="grid">Reset</button>
  </div>
</div>
<br><br>

<div class="inner cover row">
  <div>
    <% # Rendering the grid body %>
    <%= render_grid(@games_grid) %>
  </div>
</div>
<br><br>
<div class="row">
  <h2>Game library evaluated at:<br>
  <%= @gamesPrice %></h2>
</div>

app/views/games/new.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand"><%= link_to "Game Library", root_path %></h3>
    <nav>
      <ul class="nav masthead-nav">
        <li><%= link_to "Home", root_path %></a></li>
        <li><%= link_to "Games", games_path %></li>
        <li class="active"> <%= link_to "Add Game", new_game_path %></li>
      </ul>
    </nav>
  </div>
</div>

<div class="inner cover">
  <h1 class="cover-heading">Add Game</h1>
  <br>
</div>
<div class="inner cover row">
  <div class="col-lg-6 col-lg-offset-3">
    <%= form_for(@game) do |f| %>

        <%#= FORM Title %>
        <%= render partial: "shared/flash_error_messages", locals: { msgErro: @game.errors[:title],
                                                                     msgInicial: "Este campo"} %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Digite o titulo do jogo'%><br>

        <%# FORM Platform %>
        <%= render partial: "shared/flash_error_messages", locals: { msgErro: @game.errors[:platform],
                                                                     msgInicial: "Este campo"} %>
        <%= f.text_field :platform, class: 'form-control', placeholder: 'Digite a plataforma do jogo'%><br>


        <%#= FORM Gender %>
        <%= render partial: "shared/flash_error_messages", locals: { msgErro: @game.errors[:gender],
                                                                     msgInicial: "Este campo"} %>
        <%= f.text_field :gender, class: 'form-control', placeholder: 'Digite o genero do jogo'%><br>

        <%#= FORM Ano%>
        <%= render partial: "shared/flash_error_messages", locals: { msgErro: @game.errors[:year],
                                                                     msgInicial: "Este campo"} %>
        <%= f.text_field :year, class: 'form-control', placeholder: 'Digite o ano de lançamento'%><br>

        <%#= FORM Price %>
        <%= render partial: "shared/flash_error_messages", locals: { msgErro: @game.errors[:price],
                                                                     msgInicial: "Este campo"} %>
        <%= f.text_field :price, class: 'form-control', placeholder: 'Digite o preço'%><br>

        <%#= FORM Rating %>
        <%= render partial: "shared/flash_error_messages", locals: { msgErro: @game.errors[:rating],
                                                                     msgInicial: "Este campo"} %>
        <%= f.number_field :rating, class: 'form-control', placeholder: 'Digite a avaliação'%><br>


      <%= f.submit "Cadastrar jogo", class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameLibrary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <%= yield %>
          <div class="mastfoot">
            <div class="inner">
              <p>Created by <a href="https://marcelotedeschi.com" target="_blank">Marcelo T</a>, using <a href="http://getbootstrap.com" target="_blank">Bootstrap</a>.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
</body>
</html>

app/views/shared/_flash_error_messages.html.erb
<%# Partial que gera mensagens de erro separadas por virgula %>
<% if !msgErro.blank? %>
    <label class="error-text"><%= msgInicial %>
      <% msgErro.each do |m| %>
          <% if m == msgErro[-1] %>
              <%= m %>
          <% elsif m == msgErro[-2] %>
              <%= m %> e
          <% else %>
              <%= m %>,
          <% end %>
      <% end %></label>
<% end %>